### PR TITLE
Updated Histo

### PR DESCRIPTION
**Pull request by ghost**
Hello! 
I have made the sentence update to issue #131.

### CODE REVIEW

**Comment by amanmdesai** [comment]
@PaxtonDevs  Thanks a lot for opening this PR!
Looks good to me.

**Comment by ghost** [comment]
Awesome, thank you for sharing this project.

**Review by klieret — APPROVED** [review]
Thanks!

**Comment by klieret** [comment]
@all-contributors please add @PaxtonDevs for content

**Pull request merged**
