### PR TITLE
Fix the key points for each chapter

### LINKED ISSUE #26: Fix the "Key Points" for each chapter
In each section, the "Key points" at the bottom are quite empty. Such sections are a great opportunity to highlight what students should have learned and confirm if the goals were reached, or something else must be reviewed again. 

Please check the Key Points for the chapters.

### PR DESCRIPTION
**Pull request by michmx**
Hi. Here is a suggestion of key points, trying to condensate what the students must keep in mind at the end of each chapter.

### CODE REVIEW

**Comment by klieret** [comment]
I was wondering whether it was possible to add some very concrete things/commands/etc. to these, but probably there are just too many commands to memorize, right?

**Comment by michmx** [comment]
> I was wondering whether it was possible to add some very concrete things/commands/etc. to these, but probably there are just too many commands to memorize, right?

Right, I have the same feeling. That is why I propose more general remarks, hopefully useful to remind students where to come back and search a particular command/way of doing something.

**Review by klieret — APPROVED** [review]
Looks good!

**Comment by klieret** [comment]
@all-contributors please add @michmx for content

**Pull request merged**
