### PR TITLE
Add Guillermo to authors.html

### PR DESCRIPTION
**Pull request by GuillermoFidalgo**

### CODE REVIEW

**Comment by klieret** [comment]
Hi @GuillermoFidalgo   side note: you should actually be able to add authors with allcontributors by typing `@allcontributors please add @GuillermoFidalgo for content` anywhere on github :)

**Comment by GuillermoFidalgo** [comment]
Thanks!

So like this?
@allcontributors please add @GuillermoFidalgo @amorenobr @Marchela04

**Comment by GuillermoFidalgo** [comment]
Thanks!

So like this?
@allcontributors please add @GuillermoFidalgo , @amorenobr and  @Marchela04 for content

**Comment by GuillermoFidalgo** [comment]
I guess I should delete this PR since I have made one for each of the contributors. Right @klieret ?

**Comment by klieret** [comment]
> I guess I should delete this PR since I have made one for each of the contributors. Right @klieret ?

Yes, should be the same :) 

(also I hope that the different PRs don't get into merge conflicts if they are opened before merging the last one, but let's see)

**Comment by klieret** [comment]
Yes, we should only open these PRs one after each other in the future @GuillermoFidalgo . I took care of the merge conflicts :)

**Pull request closed without merging**
