### PR TITLE
Minor fixes in Markdown files

### PR DESCRIPTION
**Pull request by amangoel185**
Fixes a few spacing and minor issues in the Markdown files.

### CODE REVIEW

**Comment by klieret** [comment]
Hi @meevans1 do you have time to review this?

**Comment by klieret** [comment]
Ah wait, I just saw that most of these files are boilerplate files. So we should also modify them in the styles repository

**Review by meevans1 — APPROVED** [review]
Looks good, thanks @amangoel185 & @klieret

**Comment by klieret** [comment]
@amangoel185 could you also create a similar PR for https://github.com/hsf-training/hsf-styles ? The corresponding files are either at top level or in `bin/boilerplate`

Thanks for your contribution!

**Review by klieret — APPROVED** [review]

**Comment by amangoel185** [comment]
@klieret, Sure! I'll do that.

**Pull request merged**
