### PR TITLE
Adding a chapter on mplhep commands

### PR DESCRIPTION
**Pull request by GuillermoFidalgo**
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution.

To ensure that someone gets notified, you can also click on "Request a review" and add
the suggested person.

Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact the HSF training convenors.

You may delete these instructions from your comment.

\- HSF Training
</details>

### CODE REVIEW

**Comment by GuillermoFidalgo** [comment]
Hi @michmx 
just wanted to make sure that someone could check this PR.
Let me know of any suggestions

**Comment by GuillermoFidalgo** [comment]
Thanks for approving the other PRs @klieret could also take a look at the remaining ones?

**Comment by klieret** [comment]
Hi @GuillermoFidalgo  Unfortunately I'm currently to busy with finishing PhD stuff (and I'm completely out of the loop).... 

You could also talk to @michmx  to perhaps just give you write access to this repository (depending on how you want to collaborate on this)?

**Comment by GuillermoFidalgo** [comment]
I wanted to figure out if I could officially request a review in GitHub but I think I would need some kind of access for that as well.
@michmx could this be done?
I believe you are still in vacation. If so, is there someone else that could help?

**Comment by klieret** [comment]
Hi @GuillermoFidalgo   I've just granted your maintainer rights (check your email). You should now be able to do almost everything :)  

I think that's in the spirit of HSF being a doocracy, but I'm a bit out of the loop and don't know how you're collaborating on this (if you are multiple people and want to check each others PRs). Especially if you're the primary developer of this lesson, I think you can just merge your PRs ;)

**Comment by klieret** [comment]
> I believe you are still in vacation. If so, is there someone else that could help?

I think @wdconinc is also active here :) 

I'll be around more starting in April :)

**Comment by GuillermoFidalgo** [comment]
Thanks @klieret !

Indeed Marcela, Alexander and I are the main developers of this lesson. While I do respect the need for the pull request method requiring that owners/maintainers review the material, having the power to merge my own is also a nice thing to have.

**Comment by klieret** [comment]
Since you are the authors, you are as much owner as it gets :)    If the others want to be added as well, they can ping me.

**Pull request merged**
