### PR TITLE
Object oriented MPL episode 1 (part 2)

### LINKED ISSUE #117: OO+API for episode 1 lines 130-156
As per discussion with @klieret (in #113), need to update lines 130-156 of episode 1

### PR DESCRIPTION
**Pull request by amanmdesai**
Partially updates episode 1 lines 130-156.

**TO DO**: Modify text as per the new code

Closes #117

### CODE REVIEW

**Comment by amanmdesai** [comment]
I have modified the text upto some extent, however needs more modifications

**Review by klieret — APPROVED** [review]
Nice, thanks!

**Comment by klieret** [comment]
Ah sorry, didn't see your todo note (you can convert PRs to drafts to make it clear that it's not ready). Feel free to just open an issue or a PR if there's anything left

**Comment by amanmdesai** [comment]
no problem, there will be some minor changes, But could you also check the episode, in particular the lines ~130 to ~160 and check if more modifications are actually required.

**Pull request merged**
